export const data = [
  {
    id: 1,
    image:'/Thumbnails/download-1.jpg',
    video: 'Videos/1_Grow_up_Stage_Modul_video.mp4',
    title: 'The magic ALDI bag',
    text: 'ALDI',
    hovered: false,
  },
  {
    id: 2,
    image:'/Thumbnails/download-2.jpg',
    video: 'Videos/bmw_stage_3.mp4',
    title: 'ACC001',
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 3,
    image:'/Thumbnails/download-3.jpg',
    video: 'Videos/EasyRider_8Sec_L.mp4',
    title: "Here's to the heart.",
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 4,
    image:'/Thumbnails/download-4.jpg',
    video: 'Videos/eq_stage_video.mp4',
    title: "Magical Garage",
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 5,
    image:'/Thumbnails/download-5.jpg',
    video: 'Videos/F1_stage-1.mp4',
    title: "Easter can be so ALDI",
    text: 'ALDI',
    hovered: false,
  },
  {
    id: 6,
    image:'/Thumbnails/download-6.jpg',
    video: 'Videos/IAA_Makingof_8Sec_L.mp4',
    title: "Immortal G-Class",
    text: 'Mercedes-Benz G-Klasse',
    hovered: false,
  },
  {
    id: 7,
    image:'/Thumbnails/download-7.jpg',
    video: 'Videos/katjes_stage-1.mp4',
    title: "Vodafone ink. Netflix",
    text: 'Jiga TV',
    hovered: false,
  },
  {
    id: 8,
    image:'/Thumbnails/download-8.jpg',
    video: 'Videos/Mercedes_Leon_stage.mp4',
    title: 'The magic ALDI bag',
    text: 'ALDI',
    hovered: false,
  },
  {
    id: 9,
    image:'/Thumbnails/download-9.jpg',
    video: 'Videos/risk_1.mp4',
    title: 'ACC001',
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 10,
    image:'/Thumbnails/download-10.jpg',
    video: 'Videos/stage_g_class_dna.mp4',
    title: "Here's to the heart.",
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 11,
    image:'/Thumbnails/download-11.jpg',
    video: 'Videos/stage_xmas.mp4',
    title: "Magical Garage",
    text: 'Mercedes-Benz',
    hovered: false,
  },
  {
    id: 12,
    image:'/Thumbnails/download.jpg',
    video: 'Videos/TimeToLookUpAgain_8Sec_L.mp4',
    title: "Easter can be so ALDI",
    text: 'ALDI',
    hovered: false,
  },
]